# This file is based on:
# https://github.com/oxidize-rb/cross-gem-action

on:
  workflow_dispatch:

jobs:
  native_gem:
    name: Compile native gem
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - x86_64-linux
          # - x86_64-linux-musl
          - aarch64-linux
          # - arm-linux
          - x86_64-darwin
          - arm64-darwin
          # - x64-mingw32
          # - x64-mingw-ucrt
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - uses: oxidize-rb/cross-gem-action@v7
        with:
          platform: ${{ matrix.platform }}
          version: 'latest' # optional
          ruby-versions: '3.2' # optional
          setup: | # optional
            echo "Do something custom before compiling..."
          env: | # optional
            SOME_OTHER_ENV=some_value

      - uses: actions/download-artifact@v3
        with:
          name: cross-gem
          path: pkg/

      - name: Display structure of built gems
        run: ls -R
        working-directory: pkg/
